---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.116.72
    nexus-01:
      ansible_host: 158.160.117.112
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: glisikh
    ansible_ssh_private_key_file: "/home/glisikh/.ssh/id_ed25519"