---
all:
  hosts:
    jenkins-master-01: 
      ansible_host: 158.160.112.76
    jenkins-agent-01:
      ansible_host: 158.160.111.40
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: glisikh
    ansible_ssh_private_key_file: "/home/glisikh/.ssh/id_ed25519"